# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - projtst

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ccproject.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_cfff44c8b3694713b501a79627783df1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4e321f340e064d35b8a67663449b15cc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ccproject.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cfff44c8b3694713b501a79627783df1 }}/test:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'projtst'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_758477b8b0604ad59f1eae88c81187d4 }}
        images: 'ccproject.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cfff44c8b3694713b501a79627783df1 }}/test:${{ github.sha }}'